#![warn(clippy::pedantic)]
#![warn(clippy::nursery)]
use std::fs::File;
use std::ffi::c_long;

use rustix::fs::fstatfs;

use crate::{FileSystemKind, FileSystemName};

const ADFS_SUPER_MAGIC: c_long = 0xadf5;
const AFFS_SUPER_MAGIC: c_long = 0xadff;
const AFS_SUPER_MAGIC: c_long = 0x5346414f;
const ANON_INODE_FS_MAGIC: c_long = 0x09041934;
const AUTOFS_SUPER_MAGIC: c_long = 0x0187;
const BDEVFS_MAGIC: c_long = 0x62646576;
const BEFS_SUPER_MAGIC: c_long = 0x42465331;
const BFS_MAGIC: c_long = 0x1badface;
const BINFMTFS_MAGIC: c_long = 0x42494e4d;
const BPF_FS_MAGIC: c_long = 0xcafe4a11;
const BTRFS_SUPER_MAGIC: c_long = 0x9123683e;
const BTRFS_TEST_MAGIC: c_long = 0x73727279;
const CGROUP_SUPER_MAGIC: c_long = 0x27e0eb;
const CGROUP2_SUPER_MAGIC: c_long = 0x63677270;
const CIFS_MAGIC_NUMBER: c_long = 0xff534d42;
const CODA_SUPER_MAGIC: c_long = 0x73757245;
const COH_SUPER_MAGIC: c_long = 0x012ff7b7;
const CRAMFS_MAGIC: c_long = 0x28cd3d45;
const DEBUGFS_MAGIC: c_long = 0x64626720;
const DEVFS_SUPER_MAGIC: c_long = 0x1373;
const DEVPTS_SUPER_MAGIC: c_long = 0x1cd1;
const ECRYPTFS_SUPER_MAGIC: c_long = 0xf15f;
const EFIVARFS_MAGIC: c_long = 0xde5e81e4;
const EFS_SUPER_MAGIC: c_long = 0x00414a53;
const EXT_SUPER_MAGIC: c_long = 0x137d;
const EXT2_OLD_SUPER_MAGIC: c_long = 0xef51;
const EXT2_SUPER_MAGIC: c_long = 0xef53;
const EXT3_SUPER_MAGIC: c_long = 0xef53;
const EXT4_SUPER_MAGIC: c_long = 0xef53;
const F2FS_SUPER_MAGIC: c_long = 0xf2f52010;
const FUSE_SUPER_MAGIC: c_long = 0x65735546;
const FUTEXFS_SUPER_MAGIC: c_long = 0xbad1dea;
const HFS_SUPER_MAGIC: c_long = 0x4244;
const HOSTFS_SUPER_MAGIC: c_long = 0x00c0ffee;
const HPFS_SUPER_MAGIC: c_long = 0xf995e849;
const HUGETLBFS_MAGIC: c_long = 0x958458f6;
const ISOFS_SUPER_MAGIC: c_long = 0x9660;
const JFFS2_SUPER_MAGIC: c_long = 0x72b6;
const JFS_SUPER_MAGIC: c_long = 0x3153464a;
const MINIX_SUPER_MAGIC: c_long = 0x137f;
const MINIX_SUPER_MAGIC2: c_long = 0x138f;
const MINIX2_SUPER_MAGIC: c_long = 0x2468;
const MINIX2_SUPER_MAGIC2: c_long = 0x2478;
const MINIX3_SUPER_MAGIC: c_long = 0x4d5a;
const MQUEUE_MAGIC: c_long = 0x19800202;
const MSDOS_SUPER_MAGIC: c_long = 0x4d44;
const MTD_INODE_FS_MAGIC: c_long = 0x11307854;
const NCP_SUPER_MAGIC: c_long = 0x564c;
const NFS_SUPER_MAGIC: c_long = 0x6969;
const NILFS_SUPER_MAGIC: c_long = 0x3434;
const NSFS_MAGIC: c_long = 0x6e736673;
const NTFS_SB_MAGIC: c_long = 0x5346544e;
const OCFS2_SUPER_MAGIC: c_long = 0x7461636f;
const OPENPROM_SUPER_MAGIC: c_long = 0x9fa1;
const OVERLAYFS_SUPER_MAGIC: c_long = 0x794c7630;
const PIPEFS_MAGIC: c_long = 0x50495045;
const PROC_SUPER_MAGIC: c_long = 0x9fa0;
const PSTOREFS_MAGIC: c_long = 0x6165676c;
const QNX4_SUPER_MAGIC: c_long = 0x002f;
const QNX6_SUPER_MAGIC: c_long = 0x68191122;
const RAMFS_MAGIC: c_long = 0x858458f6;
const REISERFS_SUPER_MAGIC: c_long = 0x52654973;
const ROMFS_MAGIC: c_long = 0x7275;
const SECURITYFS_MAGIC: c_long = 0x73636673;
const SELINUX_MAGIC: c_long = 0xf97cff8c;
const SMACK_MAGIC: c_long = 0x43415d53;
const SMB_SUPER_MAGIC: c_long = 0x517b;
const SMB2_MAGIC_NUMBER: c_long = 0xfe534d42;
const SOCKFS_MAGIC: c_long = 0x534f434b;
const SQUASHFS_MAGIC: c_long = 0x73717368;
const SYSFS_MAGIC: c_long = 0x62656572;
const SYSV2_SUPER_MAGIC: c_long = 0x012ff7b6;
const SYSV4_SUPER_MAGIC: c_long = 0x012ff7b5;
const TMPFS_MAGIC: c_long = 0x01021994;
const TRACEFS_MAGIC: c_long = 0x74726163;
const UDF_SUPER_MAGIC: c_long = 0x15013346;
const UFS_MAGIC: c_long = 0x00011954;
const USBDEVICE_SUPER_MAGIC: c_long = 0x9fa2;
const V9FS_MAGIC: c_long = 0x01021997;
const VXFS_SUPER_MAGIC: c_long = 0xa501fcf5;
const XENFS_SUPER_MAGIC: c_long = 0xabba1974;
const XENIX_SUPER_MAGIC: c_long = 0x012ff7b4;
const XFS_SUPER_MAGIC: c_long = 0x58465342;
const _XIAFS_SUPER_MAGIC: c_long = 0x012fd16d;
const ZFS_SUPER_MAGIC: c_long = 0x2FC12FC1;

#[inline]
pub fn filesystem(file: &File) -> Result<FileSystemKind, std::io::Error> {
    let statfs = fstatfs(file)?;

    match statfs.f_type {
        libc::ADFS_SUPER_MAGIC => todo!(),
        libc::AFFS_SUPER_MAGIC => todo!(),
        libc::AFS_SUPER_MAGIC => todo!(),
        ANON_INODE_FS_MAGIC => todo!(),
        libc::AUTOFS_SUPER_MAGIC => todo!(),
        BDEVFS_MAGIC => todo!(),
        BEFS_SUPER_MAGIC => todo!(),
        BFS_MAGIC => todo!(),
        BINFMTFS_MAGIC => todo!(),
        libc::BPF_FS_MAGIC => todo!(),
        libc::BTRFS_SUPER_MAGIC => todo!(),
        BTRFS_TEST_MAGIC => todo!(),
        libc::CGROUP_SUPER_MAGIC => todo!(),
        libc::CGROUP2_SUPER_MAGIC => todo!(),
        CIFS_MAGIC_NUMBER => todo!(),
        libc::CODA_SUPER_MAGIC => todo!(),
        COH_SUPER_MAGIC => todo!(),
        libc::CRAMFS_MAGIC => todo!(),
        libc::DEBUGFS_MAGIC => todo!(),
        DEVFS_SUPER_MAGIC => todo!(),
        libc::DEVPTS_SUPER_MAGIC => todo!(),
        libc::ECRYPTFS_SUPER_MAGIC => todo!(),
        EFIVARFS_MAGIC => todo!(),
        libc::EFS_SUPER_MAGIC => todo!(),
        EXT_SUPER_MAGIC => todo!(),
        EXT2_OLD_SUPER_MAGIC => todo!(),
        libc::EXT2_SUPER_MAGIC => todo!(),
        libc::EXT3_SUPER_MAGIC => todo!(),
        libc::EXT4_SUPER_MAGIC => todo!(),
        libc::F2FS_SUPER_MAGIC => todo!(),
        libc::FUSE_SUPER_MAGIC => todo!(),
        libc::FUTEXFS_SUPER_MAGIC => todo!(),
        HFS_SUPER_MAGIC => todo!(),
        libc::HOSTFS_SUPER_MAGIC => todo!(),
        libc::HPFS_SUPER_MAGIC => todo!(),
        libc::HUGETLBFS_MAGIC => todo!(),
        libc::ISOFS_SUPER_MAGIC => todo!(),
        libc::JFFS2_SUPER_MAGIC => todo!(),
        JFS_SUPER_MAGIC => todo!(),
        libc::MINIX_SUPER_MAGIC => todo!(),
        libc::MINIX_SUPER_MAGIC2 => todo!(),
        libc::MINIX2_SUPER_MAGIC => todo!(),
        libc::MINIX2_SUPER_MAGIC2 => todo!(),
        libc::MINIX3_SUPER_MAGIC => todo!(),
        MQUEUE_MAGIC => todo!(),
        libc::MSDOS_SUPER_MAGIC => todo!(),
        MTD_INODE_FS_MAGIC => todo!(),
        libc::NCP_SUPER_MAGIC => todo!(),
        libc::NFS_SUPER_MAGIC => todo!(),
        libc::NILFS_SUPER_MAGIC => todo!(),
        libc::NSFS_MAGIC => todo!(),
        NTFS_SB_MAGIC => todo!(),
        libc::OCFS2_SUPER_MAGIC => todo!(),
        libc::OPENPROM_SUPER_MAGIC => todo!(),
        libc::OVERLAYFS_SUPER_MAGIC => todo!(),
        PIPEFS_MAGIC => todo!(),
        libc::PROC_SUPER_MAGIC => todo!(),
        PSTOREFS_MAGIC => todo!(),
        libc::QNX4_SUPER_MAGIC => todo!(),
        libc::QNX6_SUPER_MAGIC => todo!(),
        RAMFS_MAGIC => todo!(),
        libc::REISERFS_SUPER_MAGIC => todo!(),
        ROMFS_MAGIC => todo!(),
        libc::SECURITYFS_MAGIC => todo!(),
        libc::SELINUX_MAGIC => todo!(),
        libc::SMACK_MAGIC => todo!(),
        libc::SMB_SUPER_MAGIC => todo!(),
        SMB2_MAGIC_NUMBER => todo!(),
        SOCKFS_MAGIC => todo!(),
        SQUASHFS_MAGIC => todo!(),
        libc::SYSFS_MAGIC => todo!(),
        SYSV2_SUPER_MAGIC => todo!(),
        SYSV4_SUPER_MAGIC => todo!(),
        libc::TMPFS_MAGIC => todo!(),
        libc::TRACEFS_MAGIC => todo!(),
        libc::UDF_SUPER_MAGIC => todo!(),
        UFS_MAGIC => todo!(),
        libc::USBDEVICE_SUPER_MAGIC => todo!(),
        V9FS_MAGIC => todo!(),
        VXFS_SUPER_MAGIC => todo!(),
        libc::XENFS_SUPER_MAGIC => todo!(),
        XENIX_SUPER_MAGIC => todo!(),
        libc::XFS_SUPER_MAGIC => todo!(),
        _XIAFS_SUPER_MAGIC => todo!(),
        ZFS_SUPER_MAGIC => todo!(),
        _ => todo!(),
    }
}
